addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-git"       % "1.0.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.16")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"      % "2.2.18")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.2")
